INSERT INTO questions VALUES(1,'Geografia','Które z państw nie powstało w wyniki rozpadu Jugosławi?','Albania','Bośnia i Hercegowina','Słowenia','Chorwacja');
INSERT INTO questions VALUES(2,'Geografia','Z kim chce graniczyć Rosja?','z nikim','z Chinami','z Niemcami','z Laosem');
INSERT INTO questions VALUES(3,'Geografia','Które miasto jest stolicą Korei Północnej?','Pyongyang','Seul','Shenyang','Beijing');
INSERT INTO questions VALUES(4,'Geografia','Z iloma państwami graniczy Mongolia?','2','3','4','5');
INSERT INTO questions VALUES(5,'Geografia','Który z wymienionych krajów ma największą powierzchnię?','Peru','Boliwia','Wenezuela','Kolumbia');
INSERT INTO questions VALUES(6,'Geografia','Które z wymienionych państw nie jest państwem śródlądowym?','Etiopia','Somalia','Angola','Nigeria');
INSERT INTO questions VALUES(7,'Geografia','W którym kraju język hiszpański nie jest językiem urzędowym?','Haiti','Chile','Kuba','Panama');
INSERT INTO questions VALUES(8,'Geografia','Na jakim kontynencie leżą Andy?','Ameryka Południowa','Ameryka Północna','Azja','Afryka');
INSERT INTO questions VALUES(9,'Geografia','Które miasto jest stolicą Irlandii?','Dublin','Cardiff','Belfast','Edinburg');
INSERT INTO questions VALUES(10,'Geografia','Który europejski łańcuch górski jest najdłuższy?','Góry Skandynawskie','Apeniny','Tatry','Alpy');
INSERT INTO questions VALUES(11,'Trach','Jakiego koloru są karty odpowiedzi?','Niebieski','Czerwony','Różowy','Zielony');
INSERT INTO questions VALUES(12,'Trach','Które zagranie nie pozwala wskrzesić gracza?','Nowonarodzony','Supertrach','Wskrzeszenie','Pustak z Lustrzany Odbiciem');
INSERT INTO questions VALUES(13,'Trach','Po rzuceniu której karty atakowany gracz nie może się bronić?','Strzał w plecy','Atomowy guzik','Potężny atak ','Zmasowany Atak');
INSERT INTO questions VALUES(14,'Trach','Co powoduje karta "Chwila śmierci"?','Wszyscy gracze pozostają z jednym życiem','Umiera wybrany gracz','Sprawia że umierają gracze którzy nie mogą się obronić','Zabija wszystkich graczy');
INSERT INTO questions VALUES(15,'Trach','Ile przedmiotów może posiadać maksymalnie gracz?','Nie istnieje limit przedmiotów','3','10','2');
INSERT INTO questions VALUES(16,'Historia Polski','W którym roku Polska przyjeła chrzest?','966 r.','1025 r.','476 r.','872 r.');
INSERT INTO questions VALUES(17,'Historia Polski','Kto był ostatnim królem Polski z dynastii Piastów?','Kazimierz Wielki','Bolesław Krzywousty','Stanisław August Poniatowksi','Władysław Jagiełło');
INSERT INTO questions VALUES(18,'Historia Polski','Kogo pokonały wojska Polskie w bitwie pod Kircholmem?','Szwedów','Turków','Tatarów','Prusaków');
INSERT INTO questions VALUES(19,'Historia Polski','W jakim konflikcie zbrojnym bohaterską postawą wsławił się Rotmistrz Witold Pilecki?','II Wojnie światowej','I Wojnie światowej','Powstaniu Listopadowym','Powstaniu styczniowym');
INSERT INTO questions VALUES(20,'Historia Polski','Kiedy odbyła się bitwa pod Grunwaldem?','15.07.1410 r.','13.05.1444 r.','24.06.972 r.','12.09.1683 r.');
INSERT INTO questions VALUES(21,'Sport','Który kraj zdobył najwięcej tytułów mistrza świata w Piłce Nożnej?','Brazylia','Niemcy','Urugwaj','Włochy');
INSERT INTO questions VALUES(22,'Sport','Ile wygranych w Pucharze Świata w swojej karierze odniósł Adam Małysz?','39','46','27','53');
INSERT INTO questions VALUES(23,'Sport','Jaki sport uprawia Rafał Majka?','Kolarstwo szosowe','Pływanie','Piłkę ręczną','Koszykówkę');
INSERT INTO questions VALUES(24,'Sport','Który Polski klub triumfował w rozgrywkach Ligi Mistrzów w Piłce Ręcznej','Vive Tauron Kielce','Orlen Wisła Płock','KS Azoty Puławy','Chrobry Głogów');
INSERT INTO questions VALUES(25,'Sport','W bolidzie jakiego zespołu Robert Kubica odniósł zwycięstwo w wyścigu formuły 1 w Grand Prix Kanady w 2008 roku?','BMW Sauber','Renault','Ferrari','Maclaren Mercedes');
INSERT INTO questions VALUES(26,'Muzyka','Jaki zespół nagrał piosenki "Barcelona", "Jeden moment"?','Pectus','Video','Bracia','Feel');
INSERT INTO questions VALUES(27,'Muzyka','W jakim kraju urodziła się Ewa Farna?','Czechy','Polska','Słowacja','Niemcy');
INSERT INTO questions VALUES(28,'Muzyka','Kto jest wokalistą zespołu H.I.M?','Ville Vallo','Marco Hietala','Axl Rose','Joey Tempstr');
INSERT INTO questions VALUES(29,'Muzyka','Kto wydał album Elliminati?','Tede','Paluch','Kękę','Eminem');
INSERT INTO questions VALUES(30,'Muzyka','Skąd pochodził zepół The Beatles?','Liverpool','Mancheter','Londyn','Dublin');
INSERT INTO questions VALUES(31,'Polska','Kto wypowiedział słynne słowa "Yes, Yes, Yes!" po pierwszym podziale pieniędzy Unii Europejskiej w którym Polska wzięła udział?','Kazimierz Marcinkiewicz','Andrzej Lepper','Jarosław Kaczyński','Grzegorz Schetyna');
INSERT INTO questions VALUES(32,'Polska','W jakim polskim mieście znajduje się Sky Tower?','Wrocław','Gdańsk','Poznań','Warszawa');
INSERT INTO questions VALUES(33,'Polska','W którym z podanych miast nie odbyły się mecze Euro2012?','Kraków','Gdańsk','Wrocław','Poznań');
INSERT INTO questions VALUES(34,'Polska','Politykiem jakiej partii są Stefan Niesiołowski i Grzegorz Schetyna?','Platforma Obywatelska','Prawo i Sprawiedliwość','Polskie Stronnictwo Ludowe','Nowoczesna');
INSERT INTO questions VALUES(35,'Polska','Która z podanych kar nie jest przewidziana przez Kodeks Karny?','Mandat karny','Kara pozbawienia wolności','Grzywna','Kara ograniczenia wolności');
INSERT INTO questions VALUES(36,'Trach','Ile pustaków należy uzbierać by wygrać rozgrywkę?','5','4','3','Jest to nie możliwe.');
INSERT INTO questions VALUES(37,'Trach','Jakiego koloru są karty ataku?','Czerwony','Filoetowy','Błękitny','Żółty');
INSERT INTO questions VALUES(38,'Trach','Jaka karta nie przerywa działania Piorunu?','Schron','Nietykalny','Dezaktywacja karty','Supertrach');
INSERT INTO questions VALUES(39,'Trach','Ile Atomowych guzików znajdu się w talii kart?','2','1','Nie ma takiej karty','4');
INSERT INTO questions VALUES(40,'Trach','Jaki jest rysunek na karcie Krótkie Rączki?','Dinozaur na toalecie','Chłopiec wskazujący na swoich sąsiadów','Mała rączka','Krótkie strzałki w prawą i lewą stronę');
INSERT INTO questions VALUES(41,'Sport','Który z klubów piłkarskich najwięcej razy triumfował w Lidze Mistrzów?','Real Madryt','Bayern Monachium','AC Milan','FC Liverpool');
INSERT INTO questions VALUES(42,'Sport','W którym roku Polska wygrała mistrzostwa świata w piłce siatkowej organizowane w Polsce?','2014 r.','1970 r.','1984 r.','2002 r.');
INSERT INTO questions VALUES(43,'Sport','Który klub zdobył mistrzostwo Ligi NBA w 2016 roku?','Cleveland Cavaliers','Golden State Warriors','Boston Celtics','Miami Heat');
INSERT INTO questions VALUES(44,'Sport','Ile razy Justyna Kowalczyk zdobyła puchar świata w narciarstwie klasycznym?','4','1','3','7');
INSERT INTO questions VALUES(45,'Sport','W jakim mieście odbyły się Zimowe Igrzyska Olimpijskie w 2014 roku?','Sochi','Chamonix','Oslo','Moskwa');
INSERT INTO questions VALUES(46,'Muzyka','Ile nagród Grammy w 2017 roku zdobyła Adele?','5','Żadnej','3','4');
INSERT INTO questions VALUES(47,'Muzyka','W którym roku Edyta Górniak zajęła II miejsce w konkursie piosenki Eurowizja?','1994 r.','2004 r.','1986 r.','2000 r.');
INSERT INTO questions VALUES(48,'Muzyka','Kto skomponował cykl koncertów "IV Pory roku"?','Antonio Vivaldi','Jan Sebastian Bach','Amadeusz Mozart','Fryderyk Chopin');
INSERT INTO questions VALUES(49,'Muzyka','Kto jest wykonawcą piosenki "Deszcz na betonie"?','Taco Hemingway','Pezet','Paluch','Magik');
INSERT INTO questions VALUES(50,'Muzyka','Który zespół wykonuje piosenke "Iron Man"?','Black Sabbath','Kings of Leon','Iron Maiden','Foo Fighters');
INSERT INTO questions VALUES(51,'Historia Polski','W którym roku doszło do rozbicia dzielnicowego Polski?	','1138 r.','1226 r.','1364 r.','1095 r.');
INSERT INTO questions VALUES(52,'Historia Polski','Złotym wiekiem w dziejach Polski określa się wiek:','XVI','XV','XIV','XVIII');
INSERT INTO questions VALUES(53,'Historia Polski','W którym konflikcie zbrojnym siłami polskimi dowodził Romuald Traugutt?','Powstania styczniowego','Powstania listopadowego','Insurekcji Kościuszkowskiej','Powstania Śląskiego');
INSERT INTO questions VALUES(54,'Historia Polski','W którym Polska odzyskała niepodległość po 123 latach zaborów?','1918 r.','1945 r.','1939 r.','1914 r.');
INSERT INTO questions VALUES(55,'Historia Polski','Kto był pierwszym królem Polski?','Bolesław Chrobry','Mieszko I','Władysław Jagiełło','Władysław Łokietek');
INSERT INTO questions VALUES(56,'Polska','W którym roku Polska przystąpiła do Unii Europejskiej?','2004 r.','2000 r.','2002 r.','2006 r.');
INSERT INTO questions VALUES(57,'Polska','Kto był pierwszym prezydentem Polski po 1989 roku?','Lech Wałęsa','Aleskander Kwaśniewski','Wojciech Jaruzelski','Stanisław Tymiński');
INSERT INTO questions VALUES(58,'Polska','W którym mieście znajdue się największy port w Polsce?','Warszawa','Kraków','Gdańsk','Świnoujście');
INSERT INTO questions VALUES(59,'Polska','Jakie jest nagłębsze jezioro położone w Polsce?','Hańcza','Śniardwy','Wigry','Mamry');
INSERT INTO questions VALUES(60,'Polska','Jakie zwierzę jest w logo Bieszczadzkiego Parku Narodowergo?','Ryś','Łoś','Kozica','Niedźwiedź');
